'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AllDB_CLRLanguageMappings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppSimplicity.SchemaDiscovery.Providers.AllDB_CLRLanguageMappings", GetType(AllDB_CLRLanguageMappings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;DbTargets&gt;
        '''	&lt;DbTarget From=&quot;SQL&quot; To=&quot;SqlClient&quot;&gt;
        '''		&lt;Type From=&quot;bigint&quot; To=&quot;SqlDbType.BigInt&quot; /&gt;
        '''		&lt;Type From=&quot;binary&quot; To=&quot;SqlDbType.Binary&quot; /&gt;
        '''		&lt;Type From=&quot;bit&quot; To=&quot;SqlDbType.Bit&quot; /&gt;
        '''		&lt;Type From=&quot;char&quot; To=&quot;SqlDbType.Char&quot; /&gt;
        '''		&lt;Type From=&quot;datetime&quot; To=&quot;SqlDbType.DateTime&quot; /&gt;
        '''		&lt;Type From=&quot;decimal&quot; To=&quot;SqlDbType.Decimal&quot; /&gt;
        '''		&lt;Type From=&quot;float&quot; To=&quot;SqlDbType.Float&quot; /&gt;
        '''		&lt;Type From=&quot;image&quot; To=&quot;SqlDbType.Image&quot; /&gt;
        '''		&lt;Type From=&quot;int&quot; To=&quot;SqlDbType.Int&quot; /&gt;
        '''		 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property DbTargets() As String
            Get
                Return ResourceManager.GetString("DbTargets", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        '''&lt;Languages&gt;
        '''	&lt;Language From=&quot;SQL&quot; To=&quot;C#&quot;&gt;
        '''		&lt;Type From=&quot;bigint&quot; To=&quot;long&quot; /&gt;
        '''		&lt;Type From=&quot;binary&quot; To=&quot;object&quot; /&gt;
        '''		&lt;Type From=&quot;bit&quot; To=&quot;bool&quot; /&gt;
        '''		&lt;Type From=&quot;char&quot; To=&quot;string&quot; /&gt;
        '''		&lt;Type From=&quot;datetime&quot; To=&quot;DateTime&quot; /&gt;
        '''		&lt;Type From=&quot;decimal&quot; To=&quot;decimal&quot; /&gt;
        '''		&lt;Type From=&quot;float&quot; To=&quot;double&quot; /&gt;
        '''		&lt;Type From=&quot;image&quot; To=&quot;byte[]&quot; /&gt;
        '''		&lt;Type From=&quot;int&quot; To=&quot;int&quot; /&gt;
        '''		&lt;Type From=&quot;money&quot; To=&quot;decimal&quot; /&gt;
        '''		&lt;Type From=&quot;nchar&quot; To=&quot;string&quot; /&gt;
        '''		&lt;Type From=&quot;ntext&quot;  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property Languages() As String
            Get
                Return ResourceManager.GetString("Languages", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
