'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1433
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class LocalizableMessages
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AppSimplicity.LocalizableMessages", GetType(LocalizableMessages).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to A name for a DataService instance must be specified.
        '''</summary>
        Friend Shared ReadOnly Property DataServiceNameNotSpecified() As String
            Get
                Return ResourceManager.GetString("DataServiceNameNotSpecified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to find a datasource configuration for [{0}]. Please specify a connection string in .config file..
        '''</summary>
        Friend Shared ReadOnly Property DataSourceNotFound() As String
            Get
                Return ResourceManager.GetString("DataSourceNotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &quot;{0}&quot; is not a valid provider name. Use one of the following valid names : {1}.
        '''</summary>
        Friend Shared ReadOnly Property InvalidDataSourceName() As String
            Get
                Return ResourceManager.GetString("InvalidDataSourceName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Two or more primary keys are not allowed..
        '''</summary>
        Friend Shared ReadOnly Property MoreThanOnePrimaryKey() As String
            Get
                Return ResourceManager.GetString("MoreThanOnePrimaryKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Schema of table [{0}] must contain at least one primary key column..
        '''</summary>
        Friend Shared ReadOnly Property NoPrimaryKey() As String
            Get
                Return ResourceManager.GetString("NoPrimaryKey", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Provider name cannot be empty.  You must specify ProviderName value in connection string..
        '''</summary>
        Friend Shared ReadOnly Property ProviderNameIsEmpty() As String
            Get
                Return ResourceManager.GetString("ProviderNameIsEmpty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Conversion to string is not posible..
        '''</summary>
        Friend Shared ReadOnly Property ToStringEx() As String
            Get
                Return ResourceManager.GetString("ToStringEx", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Unable to instance command object..
        '''</summary>
        Friend Shared ReadOnly Property UnableToInstaceCommand() As String
            Get
                Return ResourceManager.GetString("UnableToInstaceCommand", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
